server:
  port: 8080

spring:
  application:
    name: authentication-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
#    show-sql: false
    database: postgresql
    properties:
      hibernate:
        generate_statistics: false
      jdbc:
        batch_size: 100
      order_inserts: true
      order_updates: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
